### ISSUE TITLE
Getting Started step 4- ctr-starlight create failure

### ISSUE THREAD

**Issue by DavidBuzatu-Marian** [mc256/starlight#24]
BUG
---
Description
---
Whilst following the 'Getting Started'  steps, on step 4 of tracing ('Collect traces on the worker for container startup.'), there seems to be an issue with the command execution.

Running:
```
sudo ctr-starlight create --optimize \
       --mount type=bind,src=/tmp/test-redis-data,dst=/data,options=rbind:rw \
    --env-file ./demo/config/all.env \
    --net-host \
    redis:6.2.1-starlight \
    redis:6.2.1-starlight \
    instance1
```
results in the following output:
```
time="Oct  8 03:05:39.951694957" level=info msg="sn service created" unique=093346
time="Oct  8 03:05:39.951759185" level=info msg="preparing snapshot" combo="redis:6.2.1-starlight" container=instance1 ref="redis:6.2.1-starlight"
time="Oct  8 03:05:39.970331241" level=info msg="prepared container snapshot" mnt="[{bind /var/lib/starlight-grpc/sfs/3/m [rw rbind]}]" snapshotter=worker-redis-6.2.1-starlight-918328-093346
time="Oct  8 03:05:39.970499958" level=info msg="added image config" path=/var/lib/starlight-grpc/sfs/redis_6.2.1-starlight.json
ctr-starlight: stat : no such file or directory
```

Detailed explanation
---
- I was able to identify the issue by looking into the `mounts.go` file. On line 121, the `withMounts` function seems to loop over all the given mounts (assuming that multiple such mounts can be given in the same command) and sends the combination of `type`, `src` and `dst` to the `parseMountFlag` function.
- The issue with this is that the `parseMountFlag` expects a string that contains the fields necessary for a mount (as mentioned above). However, what happens in the current implementation is that each field is passed in turn to this function, and therefore for the first field that does not have a `src`, the instruction:
`if stat, err := os.Stat(m.Source); err != nil` will fail, resulting in the error above

Potential Solution
---
Removing the `for` loop from the `withMounts` method and replacing it with: `mount := strings.Join(context.StringSlice("mount"), ",")` results in the creation of the container.

**However**, yet another issue arises immediately as one tries to mount this container. Due to the returned function from `withMounts` looping over the mount fields in the same manner, it will fail to create the correct mount point. This can also be fixed by removing the for loop and replacing it with `mount := strings.Join(context.StringSlice("mount"), ",")` (see note)

Final Mention
---
After this, `containerd` did indeed successfully create the container. However, when submitting the logs, the following error was displayed for the generated logs:
```
$ ctr-starlight report --server $STARLIGHT_PROXY --plain-http
ERRO[0000] cannot parse file                             file=06381.log
ERRO[0000] cannot parse file                             file=46711.log
ERRO[0000] cannot parse file                             file=52677.log
ERRO[0000] cannot parse file                             file=59089.log
ERRO[0000] cannot parse file                             file=82091.log
ERRO[0000] cannot parse file                             file=90635.log
ERRO[0000] cannot parse file                             file=91054.log
ERRO[0000] cannot parse file                             file=91121.log
INFO[0000] uploaded filesystem traces                    version=0.0.0
```
This might be due to the files being empty.

Notes
---
Code for `withMounts`:
```go
func withMounts(context *cli.Context, ctx gocontext.Context, base string) (oci.SpecOpts, error) {
	mount := strings.Join(context.StringSlice("mount"), ",")
	m, err := parseMountFlag(mount)
	if err != nil {
		return nil, err
	}
	log.G(ctx).Info("Mount: ", m.Source, "Dest: ", m.Destination)
	if stat, err := os.Stat(m.Source); err != nil {
		return nil, err
	} else {
		if stat.IsDir() {
			if err := touchDir(ctx, base, m.Destination); err != nil {
				return nil, err
			}
		} else {
			if err := touchFile(ctx, base, m.Destination); err != nil {
				return nil, err
			}
		}
	}

	return func(ctx gocontext.Context, client oci.Client, container *containers.Container, s *specs.Spec) error {
		mounts := make([]specs.Mount, 0)
		mount := strings.Join(context.StringSlice("mount"), ",")
		m, err := parseMountFlag(mount)
		if err != nil {
			return err
		}

		mounts = append(mounts, m)

		log.G(ctx).WithFields(logrus.Fields{
			"destination": m.Destination,
			"source":      m.Source,
		}).Info("mounting point")

		return oci.WithMounts(mounts)(ctx, client, container, s)
	}, nil
}
```

**Comment by mc256** [comment]
Thank you for trying out Starlight, I am looking into it.

**Comment by mc256** [comment]
@DavidBuzatu-Marian 
Thanks again for the insightful information. I am able to reproduce this issue and working on a solution. 


This seems to be a bug related to parsing the`--mount` flag. You should be able to launch the container and collect traces using this command without the `--mount` flag:
```
sudo ctr-starlight create --optimize \
    --env-file ./demo/config/all.env \
    --net-host \
    redis:6.2.1-starlight \
    redis:6.2.1-starlight \
    instance1
```

The `--mount` flag simulates we have a folder to store persistent data. It is optional anyway in this case.

I still have not yet figured out what introduced this bug and it was working. I will give you an update in two days. I am working on integrating Starlight with Kubernetes and PostgresDB backend right now on the `master` branch (sorry for the inconvenience), so please keep using tag `v0.1.1` for now. I will fix the bug and release `v0.1.2` very soon.


For issues in the  **Final Mention**,  the filesystem traces will be kept in the memory until we remove the container (i.e. gracefully unmount the StarlightFS)
```
sudo ctr container rm instance1
```
The design decision here is to have less disk operation and reduce the interference for the trace collection. After removing the container, you should be able to see non-empty traces in `/tmp/starlight-optimizer`

By the way, You could check whether the container is still running using:
```
sudo ctr container ls
```

**Comment by mc256** [comment]
@DavidBuzatu-Marian  
The bug has been resolved. Please check the latest release: `v0.1.2`.

```
git checkout v0.1.2
```

Please do not hesitate to ask me if you have further questions 😊.

**Comment by mc256** [comment]
Hi @DavidBuzatu-Marian ,

This is a good point. And I am happy that you figured out that mapping `worker1` in `/etc/hosts` can solve the issue by yourself. This is exactly what I did for my experiment environment. 

I think asking others to change the `/etc/host` configuration on the host machine may not be a good idea. So I make it read from the environment variable `STARLIGHT_PROXY`. You could use the following command to set the `--server` flag in `v0.1.3`

```shell
export STARLIGHT_PROXY=worker1.lan
ctr-starlight report --plain-http
```
