### ISSUE TITLE
random error occurs on early startup (no such file or directory)

### ISSUE THREAD

**Issue by cstria0106** [mc256/starlight#28]
I am measuring the effect of end to end delay on performance. The delay was simulated using the tc command.

<img width="450" alt="Screen Shot 2023-01-26 at 1 47 43 AM" src="https://user-images.githubusercontent.com/11474150/214626707-8e9a1f05-839c-4f3d-82dc-8be6abfc32ee.png">
<img width="700" alt="Screen Shot 2023-01-26 at 1 55 22 AM" src="https://user-images.githubusercontent.com/11474150/214628115-5ba16b11-fa37-4798-9055-15c9818442cc.png">

Containers work properly in environments without delay, but containers do not run randomly when delay is set.

<img width="1754" alt="Screen Shot 2023-01-26 at 1 58 00 AM" src="https://user-images.githubusercontent.com/11474150/214628904-255d2ea8-5c8f-4153-99cb-3201c86f0c61.png">

If I start the container after pulling all of the image, this error does not occur.
Please let me know if you need additional information for the reproducing. Thank you!

### Environment
- v0.3.1
- Followed [newbie.md](https://github.com/mc256/starlight/blob/master/docs/newbie.md) step by step (exclude adjusting the TCP window size
- Proxy(with registry) and edge node running in VirtualBox (Arch Linux)
- The RTT was set to 100ms on the edge using 'tc' Linux command

**Comment by cstria0106** [comment]
I found something that might help solve this problem.

---

I found that ReferencedFile.Ready is not set correctly in manager.go

https://github.com/mc256/starlight/blob/f4f99992dcd67c1c38867cafbd29f829361252f5/client/manager.go#L311-L317

I think it's because ReferencedFile.InPayload returns false for files included in payload, so the file is not waited for being downloaded.

It's the implementation of InPayload.
https://github.com/mc256/starlight/blob/f4f99992dcd67c1c38867cafbd29f829361252f5/util/receive/image.go#L197-L202

I [changed the function](https://github.com/cstria0106/starlight/blob/06e0ddaf5f494ff8859262466ca4343a06f992b5/util/receive/image.go#L205-L210) to return true for ReferencedFile that PayloadOrder is greater than 0

```go
func (r *ReferencedFile) InPayload() (stack int64, inPayload bool) {
	if r.PayloadOrder > 0 {
		return r.ReferenceStack, true
	}
	return -1, false
}
```

Then it worked properly.

**Comment by mc256** [comment]
Sorry for the late response. I was on vacation last week.

Thank you very much for identifying this very critical bug. I thought this issue was related to the containerd config ( in https://github.com/mc256/starlight/issues/26#issuecomment-1374969087 ), but it is more serious than that. The implantation of `InPayload` is completely wrong.

`v0.3.2` should resolve this problem.

I will work on creating unit testing to ensure all the features are functioning are working as expected. I am still doing manual testing, which is not a good approach.

**Comment by cstria0106** [comment]
I’m glad I was able to help. I have checked that the new version has resolved the error. Thank you for taking the time.
