### ISSUE TITLE
Method for Injecting Latency and Limiting Bandwidth in Starlight Evaluations

### ISSUE THREAD

**Issue by zhiyuanGH** [mc256/starlight#42]
Greetings,

I've recently read your paper and successfully used Starlight for container provisioning. I appreciate this holistic and solid work.

In your paper, you evaluated Starlight under various bandwidth and latency settings. My assumption is that you deployed Starlight and a private image registry within the same Local Area Network (LAN), as this would naturally result in high bandwidth (several GBs) and almost negligible latency (close to 0 ms). I wonder if this setup enabled you to achieve the minimal latency of 0.15ms mentioned in the paper.

Could you please clarify how you managed to limit the bandwidth and inject latency in your setup? I'm considering Linux tc as a potential method, but would appreciate your confirmation or suggestion of an alternative.

Thank you for your time and assistance.

**Comment by mc256** [comment]
Hi @zhiyuanGH ,

The minimal latency (very close to 0) is the latency between two AWS EC2 instances in the same region and the same Availability Zone. In this case, we do not use anything to limit the bandwidth. It is just the natural bandwidth between two network-optimized EC2 instances. 0.15ms is a measured value using `ping`.
https://docs.aws.amazon.com/sap/latest/general/arch-guide-architecture-guidelines-and-decisions.html#:~:text=single%2Ddigit%20millisecond

For other latencies, yes, I use the `tc` command available in Linux.
https://man7.org/linux/man-pages/man8/tc.8.html

BTW, for Section 5.4 Geo-Distributed WAN Experiment, we did not use any tools to limit the bandwidth or latency. It is also the natural latency between AWS data centers.

You are very welcome. Please let me know if you have any other questions.
